486 add linux to flat hub
asgardex/asgardex-desktop pull request #487
Opened 2024-11-11 02:56 UTC by Thorian1te

2024-12-23 00:05 UTC, beemdvp commented
Excited to see this release :tada:

2025-02-26 01:40 UTC, dynst requested changes

2025-02-26 01:40 UTC, dynst commented on org.asgardex.desktop.yml
> +id: org.asgardex.desktop
Shouldn't the application ID be something like `com.asgardex.asgardex-desktop`? asgardex.com is the project's domain, and the Flathub rules also say not to end an ID with `.desktop`.

https://www.asgardex.com/

https://docs.flathub.org/docs/for-app-authors/requirements#application-id

> - The ID must not end in generic terms like `.desktop` or `.app`. It's fine to repeat the application name in such cases.

https://docs.flathub.org/docs/for-app-authors/requirements#control-over-domain-or-repository

> - The domain must be directly related to the project or the application being submitted and the author or the developer or the project must have control over the domain. The corresponding URL must be reachable over HTTP(S).

2025-03-07 21:52 UTC, dynst commented on com.asgardex.asgardex-desktop.yml
> +runtime-version: '22.08'
`org.freedesktop.Platform` only has 'a maintenance period of two years.' 22.08 is already EOL.

https://freedesktop-sdk.gitlab.io/documentation/updating-sdk/release-notes/

2025-03-21 17:43 UTC, dynst commented on com.asgardex.asgardex-desktop.yml
> +      - cp -R $(npm root -g)/electron /app/lib
Instead of redundantly installing and bundling Electron, is it possible to just use the already-packaged Electron BaseApp, with the steps outlined here?

https://docs.flatpak.org/en/latest/electron.html

2025-03-24 00:03 UTC, Thorian1te commented on com.asgardex.asgardex-desktop.yml
> +      - cp -R $(npm root -g)/electron /app/lib
yeah definitely

2025-04-02 21:10 UTC, dynst commented on com.asgardex.asgardex-desktop.yml
> +  - --filesystem=home
There's actually no reason this needs read/write access to the whole home directory, is there? All user-imported files just go through the file picker portal, right?

https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

Since flatpak gives the sandboxed app its own `$XDG_CONFIG_HOME`, if Electron uses `$XDG_CONFIG_HOME` to determine the appData directory, everything should just work without any permissions or code changes at all: STORAGE_DIR will end up as `~/.var/app/com.asgardex.asgardex-desktop/config/ASGARDEX/storage/`.

https://www.electronjs.org/docs/latest/api/app#appgetpathname

https://github.com/asgardex/asgardex-desktop/blob/74c1ddff88fe0f06ded39dd0d4abe8cf504a9926/src/main/api/const.ts#L7-L8

2025-04-15 01:01 UTC, Thorian1te commented on com.asgardex.asgardex-desktop.yml
> +  - --filesystem=home
you are more than welcome to help get this PR completed. As displayed this is not my area of expertise 😮‍💨.

2025-04-27 19:33 UTC, dynst commented on com.asgardex.asgardex-desktop.yml
> +  - --filesystem=home
I would but I only have read-only permissions here 😅

Just deleting the entire `--filesystem=home` line should be fine though.

2025-04-27 21:34 UTC, dynst requested changes
There's an issue with dependencies: the line that runs `yarn install --immutable` looks like it fails in the Fetch step, because in the build sandbox [there is no network access](https://docs.flatpak.org/de/latest/flatpak-builder-command-reference.html). The only way to download dependencies is to declaratively specify them as [sources](https://docs.flatpak.org/en/latest/module-sources.html), which get downloaded *before* the build sandbox runs.

Other projects like [yarn-flatpak-demo](https://gitlab.com/olof-nord/yarn-flatpak-demo/-/blob/main/com.demo.yarn-flatpak-demo.yml?ref_type=heads) and [DOS Browser](https://github.com/js-dos/flatpak.dos.zone.browser.pc/blob/main/dos.zone.Browser.yaml) additionally make use of the obsolete `yarn --offline` option and the `yarn-offline-mirror` config. But their repos use [Yarn Classic](https://yarnpkg.com/migration/overview), while Asgardex uses Yarn Modern, which removed those, so copying the same solution wouldn't work here.

([YARN_ENABLE_OFFLINE_MODE=1](https://yarnpkg.com/configuration/yarnrc) looks like it might be relevant? But it doesn't solve the problem.)

The right solution is probably using a tool called [`flatpak-node-generator`](https://github.com/flatpak/flatpak-builder-tools/tree/master/node) to pin all the dependencies, which get specified as 'sources' in [the syntax that flatpak understands](https://docs.flatpak.org/en/latest/module-sources.html) (`generated-sources.json`), so that `flatpak-builder` will simply download all your dependencies beforehand.

2025-04-27 21:34 UTC, dynst commented on .github/workflows/build-flatpack.yml
> +    runs-on: ubuntu-20.04
```suggestion
    runs-on: ubuntu-22.04
```
GitHub just obsoleted the old runner image.

2025-04-27 21:34 UTC, dynst commented on com.asgardex.asgardex-desktop.yml
> +  - org.freedesktop.Sdk.Extension.node20
```suggestion
  - org.freedesktop.Sdk.Extension.node20
build-options:
  append-path: /usr/lib/sdk/node20/bin
```

Without this, `yarn` won't exist in the PATH during the build.

2025-04-27 21:34 UTC, dynst commented on com.asgardex.asgardex-desktop.yml
> +
```suggestion
```

2025-04-29 01:55 UTC, dynst commented
Combining Yarn & flatpak is currently hard to do 'the right way,' building from source, because the existing tooling only supports Yarn Classic (Yarn 1).

There's been a PR OPEN since 2021 that'll add support for Yarn 2 and Yarn 3, but even it doesn't add support for Yarn 4 (what asgardex currently uses): https://github.com/flatpak/flatpak-builder-tools/pull/252#issuecomment-2562347564

The workaround would be to have flatpak download already-built .js/.css bundles, copy them where the Electron BaseApp will run them, and skip any real build process entirely (for now).

2026-02-03 04:20 UTC, closed without merging